---
- name: "Ensuring Knockd service is stopped"
  ansible.builtin.service:
    name: "{{ fw_knockd_service_name }}"
    state: "stopped"
    enabled: false
  failed_when: false

- name: "Ensuring Knockd package is absent"
  ansible.builtin.dnf:
    name: "{{ fw_knockd_package }}"
    state: "absent"
